title: SDEV Lab
description: Software Development and Verification Methodologies Lab@Chungbuk National University
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
gems: ['jekyll-emoji']
emoji: format: emjoione-svg
ascii: true
